{% set name = "pycairo" %}
{% set version = "1.18.1" %}
{% set sha256 = "70172e58b6bad7572a3518c26729b074acdde15e6fee6cbab6d3528ad552b786" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pygobject/pycairo/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - windows.patch  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config  # [not win]
    - posix  # [win]
    - {{ compiler('c') }}
  host:
    - m2w64-pkg-config  # [win]
    - cairo
    - cython
    - pip
    - pthread-stubs
    - python
    - xorg-libx11 1.6.*
    - xorg-xproto
  run:
    - cairo
    - python

test:
  imports:
    - cairo
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://cairographics.org/pycairo/
  license: LGPL 2.1, MPL 1.1
  license_file: COPYING
  summary: 'Python bindings for the Cairo graphics library.'
  dev_url: https://github.com/pygobject/pycairo/

extra:
  recipe-maintainers:
    - pkgw
