{% set name = "pycairo" %}
{% set version = "1.20.1" %}
{% set sha256 = "1ee72b035b21a475e1ed648e26541b04e5d7e753d75ca79de8c583b25785531b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pygobject/pycairo/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - typing-test-workaround.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [py < 35]
  ignore_run_exports:
    - libglib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    # use last working meson to get PyPy build to work
    # see https://github.com/mesonbuild/meson/issues/8570
    - meson 0.55.*
    - pkg-config
    - {{ compiler('c') }}
  host:
    - cairo
    - flake8  # for testing during the build
    - glib
    - pytest  # for testing during the build
    - python
  run:
    - python

test:
  imports:
    - cairo
  requires:
    - pkg-config
  commands:
    # verify the pkgconfig files get installed
    - test -f $PREFIX/lib/pkgconfig/py3cairo.pc  # [unix]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\py3cairo.pc exit 1  # [win]

    # verify that the header can be located through pkg-config
    - test -f `pkg-config --variable=includedir --dont-define-prefix py3cairo`/pycairo/py3cairo.h  # [unix]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=includedir --dont-define-prefix py3cairo`) do if not exist "%%a/pycairo/py3cairo.h" exit 1  # [win]

about:
  home: http://cairographics.org/pycairo/
  license: LGPL-2.1-only OR MPL-1.1
  license_file: COPYING
  summary: Python bindings for the Cairo graphics library.
  dev_url: https://github.com/pygobject/pycairo/

extra:
  recipe-maintainers:
    - pkgw
    - ryanvolz
