appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: fqRGyIAWUszVNc/yhadu/R7Ux0sxhp/ECCvS53dhNT+1dqy+xXqPKHQIXDjoaL3ahG+PTSNonU0cMB66xCy2Vb+cNrEe/BhU5GeTsYr3zmGZeR5kT+b2a5xHN1nQpLeWJBuGFjX+vYGACwdUe183MYeVFgJl5KWyrmqx7hLtWtsbItWtjO07GI8P04sQ79e/vImmULbHxpdBGeWT4wKBGl3tNkhEURaevorrAvNX6l4l3OACjyCYj1eXtu4phjNY4I5aw/p3bU7fYdBiZy8bs3VqGQ/xoQd3HAOMYIDSqiZfhs8ffAH9rTCaN92XG9ypWoqcej+hVPFiWXPVYshCuant0OqYhM+ZRH+9M0KiPj7f82Yq7BdnK9K17MQhcmqZuc5SgFEtjdXkBeh9BvLKsImDA7koQtKyvNh3XgDpssY+/kkG5sfkbI4RVAsWWo2NoUD3k6r42d5ajzGPraF0LnxGx1bxayXkikx9lb6Z7AXnyjbq6ABjB3xPRWZmGkg6yO2MSP8ZAF32mDxQWNtq26VuNBC4Uhq9C/v4UYfTXxFhxuqOxJSGBb0UCSi8Ncr8/51oISJxA3b79vF59Dn4ZFkg+nnkSlzYfen1vSvZr/bcnCMlUCF168HZfQrZ2PunG7f8J1ggCQYyUcI20cxfaD2wUfknpTHKGxlaNF0VW3E=}
provider:
  win: azure
  linux_ppc64le: default
  linux_aarch64: default
conda_forge_output_validation: true
